### ISSUE TITLE
Other resources?

### ISSUE THREAD

**Issue by zedthirteen** [ktand/Armed#3]
More a few questions rather than issues. Sorry to post them here but there isn't a lot of info on the web (or I can't find it)

Are there links to resources on how to load from VS code/Platformio to the board. My last 32 bit board used a firmware.bin file on microsd but this isn't possible.

Any links to how to connect text or graphic display modules to EXP1/EXP2? There isn't room to get the two headers on from my RepRapDiscount Smart Controller. I'm loading KiCad now to try to look at the schematics to try and understand pinouts. I will try to connect through 20 pin IDC connector.

Also, there are a lot of undocumented solder bridge points on the underside of the board. Any descriptions for these? I need to configure for FYSTEC TMC2130's for sensorless homing. Perhaps KiCad schematic will help me with these once I get it up and running

NB. I have KiCad installed now but I think too much information is missing from schematic without the missing lib files

**Comment by ktand** [comment]
The missing libraries issue is fixed.
